# Generated by Django 6.0.4 on 2026-07-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://alcaratello.com/wp-content/uploads/2021/03/meal-placeholder.jpg', max_length=500),
        ),
    ]
