# Generated by Django 6.0.7 on 2026-09-08 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_item_item_name_alter_item_item_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user_name', 'item_price'], name='myapp_item_user_na_18bfbe_idx'),
        ),
    ]
