# Generated by Django 6.0.7 on 2026-09-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_item_deleted_at_item_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
